const fortune = [
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A feather in the hand is better than a bird in the air.",
    "A fresh start will put you on your way.",
    "A friend asks only for your time, not your money.",
    "A friend is a present you give yourself.",
    "A gambler not only will lose what he has, but also will lose what he doesn’t have.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good friendship is often more important than a passionate romance.",
    "A good time to finish up old tasks.",
    "A hunch is creativity trying to tell you something.",
    "A lifetime friend shall soon be made.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A new perspective will come with the new year.",
    "A person is never too old to learn.",
    "A person of words and not deeds is like a garden full of weeds.",
    "A pleasant surprise is waiting for you.",
    "A short pencil is usually better than a long memory any day.",
    "A small donation is call for. It’s the right thing to do.",
    "A smile is your personal welcome mat.",
    "A smooth long journey! Great expectations.",
    "A soft voice may be awfully persuasive.",
    "A truly rich life contains love and art in abundance.",
    "Accept something that you cannot change, and you will feel better.",
    "Adventure can be real happiness.",
    "Advice is like kissing. It costs nothing and is a pleasant thing to do.",
    "Advice, when most needed, is least heeded.",
    "All will go well with your new project.",
    "All your hard work will soon pay off.",
    "Allow compassion to guide your decisions.",
    "An acquaintance of the past will affect you in the near future.",
    "An agreeable romance might begin to take on the appearance.",
    "An important person will offer you support.",
    "An inch of time is an inch of gold.",
    "An unexpected relationship will become permanent.",
    "Anger begins with folly, and ends with regret.",
    "Anger is the seed for war. Understanding is the seed for peace.",
    "Any decision you have to make tomorrow is a good decision.",
    "At the touch of love, everyone becomes a poet.",
    "Be careful or you could fall for some tricks today.",
    "Beauty in its various forms appeals to you.",
    "Because you demand more from yourself, others respect you deeply.",
    "Believe in yourself and others will too.",
    "Believe it can be done.",
    "Better ask twice than lose yourself once.",
    "Bide your time, for success is near.",
    "Change is happening in your life, so go with the flow!",
    "Character is who you are when no one is watching.",
    "Charm is a way of getting the answer yes without having asked any clear question.",
    "Choose a path that offers the greatest joy.",
    "Commitment is the first step to happiness.",
    "Concentrate on the happiness that is already in your life.",
    "Confidence is the key to unlocking your potential.",
    "Conquer your fears or they will conquer you.",
    "Considerable fortune awaits you.",
    "Courage is not the absence of fear; it is the conquest of it.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Dare to dream, hope, believe, seek, feel, find, and love.",
    "Decide what you want and go for it.",
    "Do not fear what you don’t know.",
    "Do not let ambitions overshadow small success.",
    "Do not make extra work for yourself.",
    "Do not underestimate yourself. Human beings have unlimited potentials.",
    "Don’t let friends down when they need you the most.",
    "Don’t let the past and useless detail choke your existence.",
    "Don’t let your limitations overshadow your talents.",
    "Don’t worry; prosperity will knock on your door soon.",
    "Each day, compel yourself to do something you would rather not do.",
    "Education is the ability to meet life’s situations.",
    "Embrace this love relationship you have!",
    "Emulate what you admire in your parents.",
    "Emulate what you respect in your friends.",
    "Every flower blooms in its own sweet time.",
    "Every wise man started out by asking many questions.",
    "Everyday in your life is a special occasion.",
    "Everything will now come your way.",
    "Excellence is the difference between what I do and what I am capable of.",
    "Exercise caution in your business affairs.",
    "Expect much of yourself and little of others.",
    "Failure is the chance to do better next time.",
    "Faith is knowing there is an ocean because you have seen a brook.",
    "Fear and desire – two sides of the same coin.",
    "Fearless courage is the foundation of victory.",
    "Follow the middle path. Neither extreme will make you happy.",
    "For hate is never conquered by hate. Hate is conquered by love.",
    "Fortune favors the brave.",
    "Fortune not only knocks but sometimes kicks the door down.",
    "Friends long absent are coming back to you.",
    "Friendship is an ocean that you cannot see the bottom.",
    "From now on your kindness will lead you to success.",
    "Get your mind set… confidence will lead you on.",
    "Give to the world the best you have, and the best will come back to you.",
    "Happiness begins with facing life with a smile and a wink.",
    "Happiness comes from a good life.",
    "Hard work pays off in the future, laziness pays off now.",
    "Have a beautiful day.",
    "He who knows he has enough is rich.",
    "Health is greater than wealth.",
    "Help! I’m being held prisoner in a fortune cookie factory.",
    "Hold on to the dreams of your youth.",
    "If a true sense of value is to be yours it must come through service.",
    "If certainty were truth, we would never learn.",
    "If you continually give, you will continually have.",
    "If you look back, you’ll soon be going that way.",
    "If you think you can, you can.",
    "If you wish to see the best in others, show the best of yourself.",
    "If your desires are not extravagant, they will be granted.",
    "Ignore previous cookie.",
    "In the end, all things will be known.",
    "Invest time and energy to everything you pursue.",
    "It is better to be an optimist and be proven a fool than to be a pessimist and be proven right.",
    "It is honorable to stand up for what is right, however unpopular it seems.",
    "It is now, and in this world, that we must live.",
    "It is worth reviewing some old lessons.",
    "It takes courage to admit fault.",
    "It’s not the amount of time you devote, but what you devote to the time that counts.",
    "Joy is in the journey, not in the destination.",
    "Keep your eye out for someone special.",
    "Keep your feet on the ground even though friends flatter you.",
    "Knowledge is priceless.",
    "Let the deeds speak.",
    "Life is a journey. Enjoy the ride.",
    "Life is too short to waste time hating anyone.",
    "Life’s challenges are not supposed to paralyze you; they’re supposed to help you discover who you are.",
    "Listen to everyone. Ideas come from everywhere.",
    "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    "Love is a warm fire to keep the soul warm.",
    "Love is not just looking at each other, it’s looking in the same direction.",
    "Many will travel to hear you speak."
];

function getRandomIndex(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function getLuckyNumber() {
    let luckyNumber = Math.floor(Math.random() * 130);
    return luckyNumber;
}


console.log(`🌟 Fortune: ${getRandomIndex(fortune)}`);
console.log(`🔢 Lucky Number: ${getLuckyNumber()}`);
